TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += psCaen_proto.db
DB += psCaenN1470.db
DB += psCaenN1470_Simu.db
DB += psCAEN.substitutions

#=======================================
include $(TOP)/configure/RULES
